import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/shadcn/NavigationMenu";
import { Toaster } from "sonner";
import { BreadcrumbComponent } from "@/components/forms/template/Breadcrumb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div className="container mx-auto px-4 min-h-screen flex flex-col">
          <div className="p-5">
            <Navigation />
          </div>
          <div className="flex flex-col gap-4">
            <BreadcrumbComponent />
            {children}
            <Toaster className="text-neutral-950" />
          </div>
        </div>
      </body>
    </html>
  );
}
